query TokensAndPricesUniswapV2($tokensToHide: ID!, $blockT1D: Int!, $blockT2D: Int!, $blockT1W: Int!) {
  tokens_current: tokens(
    where: { id_not_in: [$tokensToHide] }
    orderBy: tradeVolumeUSD
    orderDirection: desc
    first: 50
    subgraphError: allow
  ) {
    ...tokenFields
  }
  tokens_t1D: tokens(
    where: { id_not_in: [$tokensToHide] }
    orderBy: tradeVolumeUSD
    orderDirection: desc
    first: 50
    block: { number: $blockT1D }
    subgraphError: allow
  ) {
    ...tokenFields
  }
  tokens_t2D: tokens(
    where: { id_not_in: [$tokensToHide] }
    orderBy: tradeVolumeUSD
    orderDirection: desc
    first: 50
    block: { number: $blockT2D }
    subgraphError: allow
  ) {
    ...tokenFields
  }
  tokens_t1W: tokens(
    where: { id_not_in: [$tokensToHide] }
    orderBy: tradeVolumeUSD
    orderDirection: desc
    first: 50
    block: { number: $blockT1W }
    subgraphError: allow
  ) {
    ...tokenFields
  }
  price_current: bundles(first: 1, subgraphError: allow) {
    ...priceField
  }
  price_t1D: bundles(first: 1, block: { number: $blockT1D }, subgraphError: allow) {
    ...priceField
  }
  price_t2D: bundles(first: 1, block: { number: $blockT2D }, subgraphError: allow) {
    ...priceField
  }
  price_t1W: bundles(first: 1, block: { number: $blockT1W }, subgraphError: allow) {
    ...priceField
  }
}
fragment tokenFields on Token {
  id
  symbol
  name
  derivedETH
  tradeVolumeUSD
  totalLiquidity
}
fragment priceField on Bundle {
  ethPrice
}
